{"address":null,"code":"EADDRINUSE","errno":-4091,"level":"error","message":"Uncaught Exception: bind EADDRINUSE null:6388","port":6388,"service":"vesta-backend","stack":"Error: bind EADDRINUSE null:6388\n    at listenOnPrimaryHandle (node:net:2018:18)\n    at shared (node:internal/cluster/child:157:3)\n    at Worker.<anonymous> (node:internal/cluster/child:110:7)\n    at process.onInternalMessage (node:internal/cluster/utils:49:5)\n    at process.emit (node:events:530:35)\n    at process.emit (node:domain:489:12)\n    at emit (node:internal/child_process:949:14)\n    at process.processTicksAndRejections (node:internal/process/task_queues:91:21)","syscall":"bind","timestamp":"2025-04-06T18:21:31.891Z"}
{"address":null,"code":"EADDRINUSE","errno":-4091,"level":"error","message":"Uncaught Exception: bind EADDRINUSE null:6388","port":6388,"service":"vesta-backend","stack":"Error: bind EADDRINUSE null:6388\n    at listenOnPrimaryHandle (node:net:2018:18)\n    at shared (node:internal/cluster/child:157:3)\n    at Worker.<anonymous> (node:internal/cluster/child:110:7)\n    at process.onInternalMessage (node:internal/cluster/utils:49:5)\n    at process.emit (node:events:530:35)\n    at process.emit (node:domain:489:12)\n    at emit (node:internal/child_process:949:14)\n    at process.processTicksAndRejections (node:internal/process/task_queues:91:21)","syscall":"bind","timestamp":"2025-04-06T18:21:31.897Z"}
{"address":null,"code":"EADDRINUSE","errno":-4091,"level":"error","message":"Uncaught Exception: bind EADDRINUSE null:6388","port":6388,"service":"vesta-backend","stack":"Error: bind EADDRINUSE null:6388\n    at listenOnPrimaryHandle (node:net:2018:18)\n    at shared (node:internal/cluster/child:157:3)\n    at Worker.<anonymous> (node:internal/cluster/child:110:7)\n    at process.onInternalMessage (node:internal/cluster/utils:49:5)\n    at process.emit (node:events:530:35)\n    at process.emit (node:domain:489:12)\n    at emit (node:internal/child_process:949:14)\n    at process.processTicksAndRejections (node:internal/process/task_queues:91:21)","syscall":"bind","timestamp":"2025-04-06T18:21:31.897Z"}
{"address":null,"code":"EADDRINUSE","errno":-4091,"level":"error","message":"Uncaught Exception: bind EADDRINUSE null:6388","port":6388,"service":"vesta-backend","stack":"Error: bind EADDRINUSE null:6388\n    at listenOnPrimaryHandle (node:net:2018:18)\n    at shared (node:internal/cluster/child:157:3)\n    at Worker.<anonymous> (node:internal/cluster/child:110:7)\n    at process.onInternalMessage (node:internal/cluster/utils:49:5)\n    at process.emit (node:events:530:35)\n    at process.emit (node:domain:489:12)\n    at emit (node:internal/child_process:949:14)\n    at process.processTicksAndRejections (node:internal/process/task_queues:91:21)","syscall":"bind","timestamp":"2025-04-06T18:21:31.895Z"}
{"address":null,"code":"EADDRINUSE","errno":-4091,"level":"error","message":"Uncaught Exception: bind EADDRINUSE null:6388","port":6388,"service":"vesta-backend","stack":"Error: bind EADDRINUSE null:6388\n    at listenOnPrimaryHandle (node:net:2018:18)\n    at shared (node:internal/cluster/child:157:3)\n    at Worker.<anonymous> (node:internal/cluster/child:110:7)\n    at process.onInternalMessage (node:internal/cluster/utils:49:5)\n    at process.emit (node:events:530:35)\n    at process.emit (node:domain:489:12)\n    at emit (node:internal/child_process:949:14)\n    at process.processTicksAndRejections (node:internal/process/task_queues:91:21)","syscall":"bind","timestamp":"2025-04-06T18:21:31.906Z"}
{"address":null,"code":"EADDRINUSE","errno":-4091,"level":"error","message":"Uncaught Exception: bind EADDRINUSE null:6388","port":6388,"service":"vesta-backend","stack":"Error: bind EADDRINUSE null:6388\n    at listenOnPrimaryHandle (node:net:2018:18)\n    at shared (node:internal/cluster/child:157:3)\n    at Worker.<anonymous> (node:internal/cluster/child:110:7)\n    at process.onInternalMessage (node:internal/cluster/utils:49:5)\n    at process.emit (node:events:530:35)\n    at process.emit (node:domain:489:12)\n    at emit (node:internal/child_process:949:14)\n    at process.processTicksAndRejections (node:internal/process/task_queues:91:21)","syscall":"bind","timestamp":"2025-04-06T18:21:31.904Z"}
{"address":null,"code":"EADDRINUSE","errno":-4091,"level":"error","message":"Uncaught Exception: bind EADDRINUSE null:6388","port":6388,"service":"vesta-backend","stack":"Error: bind EADDRINUSE null:6388\n    at listenOnPrimaryHandle (node:net:2018:18)\n    at shared (node:internal/cluster/child:157:3)\n    at Worker.<anonymous> (node:internal/cluster/child:110:7)\n    at process.onInternalMessage (node:internal/cluster/utils:49:5)\n    at process.emit (node:events:530:35)\n    at process.emit (node:domain:489:12)\n    at emit (node:internal/child_process:949:14)\n    at process.processTicksAndRejections (node:internal/process/task_queues:91:21)","syscall":"bind","timestamp":"2025-04-06T18:21:31.892Z"}
{"address":null,"code":"EADDRINUSE","errno":-4091,"level":"error","message":"Uncaught Exception: bind EADDRINUSE null:6388","port":6388,"service":"vesta-backend","stack":"Error: bind EADDRINUSE null:6388\n    at listenOnPrimaryHandle (node:net:2018:18)\n    at shared (node:internal/cluster/child:157:3)\n    at Worker.<anonymous> (node:internal/cluster/child:110:7)\n    at process.onInternalMessage (node:internal/cluster/utils:49:5)\n    at process.emit (node:events:530:35)\n    at process.emit (node:domain:489:12)\n    at emit (node:internal/child_process:949:14)\n    at process.processTicksAndRejections (node:internal/process/task_queues:91:21)","syscall":"bind","timestamp":"2025-04-06T18:21:31.890Z"}
{"address":"::","code":"EADDRINUSE","errno":-4091,"level":"error","message":"Uncaught Exception: listen EADDRINUSE: address already in use :::6388","port":6388,"service":"vesta-backend","stack":"Error: listen EADDRINUSE: address already in use :::6388\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at file:///C:/Users/shuga/OneDrive/Desktop/Vesta/vesta-repo/Vesta/vestaBackend/server.js:230:12\n    at ModuleJob.run (node:internal/modules/esm/module_job:271:25)\n    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:578:26)\n    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:116:5)","syscall":"listen","timestamp":"2025-04-06T18:22:38.680Z"}
{"address":"::","code":"EADDRINUSE","errno":-4091,"level":"error","message":"Uncaught Exception: listen EADDRINUSE: address already in use :::6388","port":6388,"service":"vesta-backend","stack":"Error: listen EADDRINUSE: address already in use :::6388\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at file:///C:/Users/shuga/OneDrive/Desktop/Vesta/vesta-repo/Vesta/vestaBackend/server.js:230:12\n    at ModuleJob.run (node:internal/modules/esm/module_job:271:25)\n    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:578:26)\n    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:116:5)","syscall":"listen","timestamp":"2025-04-06T18:27:12.016Z"}
{"address":"::","code":"EADDRINUSE","errno":-4091,"level":"error","message":"Uncaught Exception: listen EADDRINUSE: address already in use :::6388","port":6388,"service":"vesta-backend","stack":"Error: listen EADDRINUSE: address already in use :::6388\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at file:///C:/Users/shuga/OneDrive/Desktop/Vesta/vesta-repo/Vesta/vestaBackend/server.js:230:12\n    at ModuleJob.run (node:internal/modules/esm/module_job:271:25)\n    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:578:26)\n    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:116:5)","syscall":"listen","timestamp":"2025-04-06T18:30:43.224Z"}
{"address":"::","code":"EADDRINUSE","errno":-4091,"level":"error","message":"Uncaught Exception: listen EADDRINUSE: address already in use :::6388","port":6388,"service":"vesta-backend","stack":"Error: listen EADDRINUSE: address already in use :::6388\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at file:///C:/Users/shuga/OneDrive/Desktop/Vesta/vesta-repo/Vesta/vestaBackend/server.js:244:12\n    at ModuleJob.run (node:internal/modules/esm/module_job:271:25)\n    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:578:26)\n    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:116:5)","syscall":"listen","timestamp":"2025-04-06T18:31:11.726Z"}
{"address":"::","code":"EADDRINUSE","errno":-4091,"level":"error","message":"Uncaught Exception: listen EADDRINUSE: address already in use :::6388","port":6388,"service":"vesta-backend","stack":"Error: listen EADDRINUSE: address already in use :::6388\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at file:///C:/Users/shuga/OneDrive/Desktop/Vesta/vesta-repo/Vesta/vestaBackend/server.js:244:12\n    at ModuleJob.run (node:internal/modules/esm/module_job:271:25)\n    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:578:26)\n    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:116:5)","syscall":"listen","timestamp":"2025-04-06T18:31:44.738Z"}
{"address":"::","code":"EADDRINUSE","errno":-4091,"level":"error","message":"Uncaught Exception: listen EADDRINUSE: address already in use :::6388","port":6388,"service":"vesta-backend","stack":"Error: listen EADDRINUSE: address already in use :::6388\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at initializeServer (file:///C:/Users/shuga/OneDrive/Desktop/Vesta/vesta-repo/Vesta/vestaBackend/server.js:252:14)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","syscall":"listen","timestamp":"2025-04-06T18:33:35.830Z"}
{"level":"error","message":"Uncaught Exception: metrics.requestLatency.record is not a function","service":"vesta-backend","stack":"TypeError: metrics.requestLatency.record is not a function\n    at ServerResponse.<anonymous> (file:///C:/Users/shuga/OneDrive/Desktop/Vesta/vesta-repo/Vesta/vestaBackend/utils/monitoring.js:64:28)\n    at ServerResponse.emit (node:events:530:35)\n    at ServerResponse.emit (node:domain:489:12)\n    at onFinish (node:_http_outgoing:1081:10)\n    at afterWrite (node:internal/streams/writable:710:5)\n    at afterWriteTick (node:internal/streams/writable:696:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:89:21)","timestamp":"2025-04-07T06:26:23.187Z"}
{"level":"error","message":"Uncaught Exception: metrics.requestLatency.update is not a function","service":"vesta-backend","stack":"TypeError: metrics.requestLatency.update is not a function\n    at ServerResponse.<anonymous> (file:///C:/Users/shuga/OneDrive/Desktop/Vesta/vesta-repo/Vesta/vestaBackend/utils/monitoring.js:68:28)\n    at ServerResponse.emit (node:events:530:35)\n    at ServerResponse.emit (node:domain:489:12)\n    at onFinish (node:_http_outgoing:1081:10)\n    at afterWrite (node:internal/streams/writable:710:5)\n    at afterWriteTick (node:internal/streams/writable:696:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:89:21)","timestamp":"2025-04-07T06:30:16.918Z"}
{"level":"error","message":"Uncaught Exception: metrics.requestLatency.record is not a function","service":"vesta-backend","stack":"TypeError: metrics.requestLatency.record is not a function\n    at ServerResponse.<anonymous> (file:///C:/Users/shuga/OneDrive/Desktop/Vesta/vesta-repo/Vesta/vestaBackend/utils/monitoring.js:67:28)\n    at ServerResponse.emit (node:events:530:35)\n    at ServerResponse.emit (node:domain:489:12)\n    at onFinish (node:_http_outgoing:1081:10)\n    at afterWrite (node:internal/streams/writable:710:5)\n    at afterWriteTick (node:internal/streams/writable:696:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:89:21)","timestamp":"2025-04-07T06:32:40.827Z"}
{"level":"error","message":"Uncaught Exception: metrics.requestLatency.set is not a function","service":"vesta-backend","stack":"TypeError: metrics.requestLatency.set is not a function\n    at ServerResponse.<anonymous> (file:///C:/Users/shuga/OneDrive/Desktop/Vesta/vesta-repo/Vesta/vestaBackend/utils/monitoring.js:67:28)\n    at ServerResponse.emit (node:events:530:35)\n    at ServerResponse.emit (node:domain:489:12)\n    at onFinish (node:_http_outgoing:1081:10)\n    at afterWrite (node:internal/streams/writable:710:5)\n    at afterWriteTick (node:internal/streams/writable:696:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:89:21)","timestamp":"2025-04-07T06:38:30.891Z"}
{"level":"error","message":"Uncaught Exception: Cannot read properties of undefined (reading 'value')","service":"vesta-backend","stack":"TypeError: Cannot read properties of undefined (reading 'value')\n    at ServerResponse.<anonymous> (file:///C:/Users/shuga/OneDrive/Desktop/Vesta/vesta-repo/Vesta/vestaBackend/utils/monitoring.js:84:42)\n    at ServerResponse.emit (node:events:530:35)\n    at ServerResponse.emit (node:domain:489:12)\n    at onFinish (node:_http_outgoing:1081:10)\n    at afterWrite (node:internal/streams/writable:710:5)\n    at afterWriteTick (node:internal/streams/writable:696:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:89:21)","timestamp":"2025-04-07T06:40:01.143Z"}
{"level":"error","message":"Uncaught Exception: metrics.errorRate.mark is not a function","service":"vesta-backend","stack":"TypeError: metrics.errorRate.mark is not a function\n    at ServerResponse.<anonymous> (file:///C:/Users/shuga/OneDrive/Desktop/Vesta/vesta-repo/Vesta/vestaBackend/server.js:60:25)\n    at ServerResponse.emit (node:events:530:35)\n    at ServerResponse.emit (node:domain:489:12)\n    at onFinish (node:_http_outgoing:1081:10)\n    at callback (node:internal/streams/writable:766:21)\n    at afterWrite (node:internal/streams/writable:710:5)\n    at afterWriteTick (node:internal/streams/writable:696:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:89:21)","timestamp":"2025-04-07T06:42:38.841Z"}
{"level":"error","message":"Uncaught Exception: metrics.errorRate.mark is not a function","service":"vesta-backend","stack":"TypeError: metrics.errorRate.mark is not a function\n    at ServerResponse.<anonymous> (file:///C:/Users/shuga/OneDrive/Desktop/Vesta/vesta-repo/Vesta/vestaBackend/server.js:60:25)\n    at ServerResponse.emit (node:events:530:35)\n    at ServerResponse.emit (node:domain:489:12)\n    at onFinish (node:_http_outgoing:1081:10)\n    at callback (node:internal/streams/writable:766:21)\n    at afterWrite (node:internal/streams/writable:710:5)\n    at afterWriteTick (node:internal/streams/writable:696:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:89:21)","timestamp":"2025-04-07T06:44:29.559Z"}
{"level":"error","message":"Uncaught Exception: metrics.errorRate.mark is not a function","service":"vesta-backend","stack":"TypeError: metrics.errorRate.mark is not a function\n    at ServerResponse.<anonymous> (file:///C:/Users/shuga/OneDrive/Desktop/Vesta/vesta-repo/Vesta/vestaBackend/server.js:60:25)\n    at ServerResponse.emit (node:events:530:35)\n    at ServerResponse.emit (node:domain:489:12)\n    at onFinish (node:_http_outgoing:1081:10)\n    at callback (node:internal/streams/writable:766:21)\n    at afterWrite (node:internal/streams/writable:710:5)\n    at afterWriteTick (node:internal/streams/writable:696:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:89:21)","timestamp":"2025-04-07T06:47:03.314Z"}
{"level":"error","message":"Uncaught Exception: metrics.errorRate.mark is not a function","service":"vesta-backend","stack":"TypeError: metrics.errorRate.mark is not a function\n    at ServerResponse.<anonymous> (file:///C:/Users/shuga/OneDrive/Desktop/Vesta/vesta-repo/Vesta/vestaBackend/server.js:60:25)\n    at ServerResponse.emit (node:events:530:35)\n    at ServerResponse.emit (node:domain:489:12)\n    at onFinish (node:_http_outgoing:1081:10)\n    at callback (node:internal/streams/writable:766:21)\n    at afterWrite (node:internal/streams/writable:710:5)\n    at afterWriteTick (node:internal/streams/writable:696:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:89:21)","timestamp":"2025-04-07T06:47:03.355Z"}
{"level":"error","message":"Uncaught Exception: metrics.errorRate.mark is not a function","service":"vesta-backend","stack":"TypeError: metrics.errorRate.mark is not a function\n    at ServerResponse.<anonymous> (file:///C:/Users/shuga/OneDrive/Desktop/Vesta/vesta-repo/Vesta/vestaBackend/server.js:60:25)\n    at ServerResponse.emit (node:events:530:35)\n    at ServerResponse.emit (node:domain:489:12)\n    at onFinish (node:_http_outgoing:1081:10)\n    at callback (node:internal/streams/writable:766:21)\n    at afterWrite (node:internal/streams/writable:710:5)\n    at afterWriteTick (node:internal/streams/writable:696:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:89:21)","timestamp":"2025-04-07T06:50:00.242Z"}
{"level":"error","message":"Uncaught Exception: metrics.errorRate.mark is not a function","service":"vesta-backend","stack":"TypeError: metrics.errorRate.mark is not a function\n    at ServerResponse.<anonymous> (file:///C:/Users/shuga/OneDrive/Desktop/Vesta/vesta-repo/Vesta/vestaBackend/server.js:60:25)\n    at ServerResponse.emit (node:events:530:35)\n    at ServerResponse.emit (node:domain:489:12)\n    at onFinish (node:_http_outgoing:1081:10)\n    at callback (node:internal/streams/writable:766:21)\n    at afterWrite (node:internal/streams/writable:710:5)\n    at afterWriteTick (node:internal/streams/writable:696:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:89:21)","timestamp":"2025-04-07T06:53:34.561Z"}
{"address":"::","code":"EADDRINUSE","errno":-4091,"level":"error","message":"Uncaught Exception: listen EADDRINUSE: address already in use :::6388","port":6388,"service":"vesta-backend","stack":"Error: listen EADDRINUSE: address already in use :::6388\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at initializeServer (file:///C:/Users/shuga/OneDrive/Desktop/Vesta/vesta-repo/Vesta/vestaBackend/server.js:387:14)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","syscall":"listen","timestamp":"2025-04-07T12:38:48.315Z"}
